export const FETCH_PRODUCT_VARIATION = {
	FETCH_PRODUCT_VARIATION_INITIAL: "FETCH_PRODUCT_VARIATION_INITIAL",
	FETCH_PRODUCT_VARIATION_FAIL: "FETCH_PRODUCT_VARIATION_FAIL",
	FETCH_PRODUCT_VARIATION_LOADING: "FETCH_PRODUCT_VARIATION_LOADING",
	FETCH_PRODUCT_VARIATION_SUCCESS: "FETCH_PRODUCT_VARIATION_SUCCESS"
}